### ISSUE TITLE
Validate config parameters

### ISSUE THREAD

**Issue by gtracy** [gtracy/slack-stuart#3]
When Stuart starts, make an attempt to validate the config.js file to give the dev a heads up when things don't look right. 

- search for "FIXME" references?
- is there a way to test the Slack inbound webhook without pushing data?

**Comment by sprak3000** [comment]
@gtracy To test the inbound webhook, you could send a message to a channel that is highly unlikely to exist (e.g., `#noonewouldeverpickthisname`). Slack should respond back with an `Invalid channel specified` message.
