### ISSUE TITLE
Add default channel to the plugin configuration

### ISSUE THREAD

**Issue by gtracy** [gtracy/slack-stuart#8]
The default channel for a plugin is hard-coded inside the plugin. It would be nice to just add it to the plugin configuration to consolidate configuration.

**Comment by sprak3000** [comment]
I've opened a PR to address this item. Thought about naming the key `defaultChannel` but went with `channel` where "default" felt a bit redundant.

**Comment by gtracy** [comment]
nice. i'll take a look this weekend.
